- app/coffee/DocManager.coffee
- app/coffee/MongoManager.coffee
- test/unit/coffee/DocManagerTests.coffee
- test/unit/coffee/MongoManagerTests.coffee
- docs are written to project collection then doc collection
- deletes used to insert into doc collection, now its the same upsert
with deleted = true
- does not set delted = false for new docs as it is not needed, save space
- changed delete to be seperate update on mongo
> Write docs to do collection and project collection

- app/coffee/DocManager.coffee
- test/unit/coffee/DocManagerTests.coffee
the current getAllNonDeletedDocs method makes 2 queries to mongo, one to check if any are inS3 and then one to load the data.  This will cause the doc objects to be loaded twice in mongo.
this patch changes the order to be optimistic, so the docs are returned immediately if none are in s3, and only unarchived otherwise.
the getDoc method for a single document is already optimistic.
> optimise get all docs

- app/coffee/DocManager.coffee
- app/coffee/HttpController.coffee
We log out the doc lines here for a feeling of 'safety', but I don't recall ever actually needing to look in the log to recover anything.
If we do find we need some way to record what was written and read from Mongo here, we should explore proper data stores for this sort of thing, e.g. Mongo truncated collections, or similar. Logging to disk isn't the way to do this, as we are finding out.
> Don't log out doc lines and ranges

- app/coffee/RangeManager.coffee
- config/settings.defaults.coffee
- package.json
Makes this service compatible with https://github.com/sharelatex/sharelatex-dev-environment
Allows other service's locations to be passed in via environment variables which are provided by docker-compose.
Also provides an `npm run start` script as a common entry point to all services via docker-compose.
>  Provide hosts as environment settings and add npm run start script

- .travis.yml
So travis picks instead the version from .nvmrc
The build is currently failing because it's using an old version of node
https://travis-ci.org/sharelatex/document-updater-sharelatex/builds/329565434
If we don't specify a version in travis.yml travisci uses the one in .nvmrc.
https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#Specifying-Node.js-versions-using-.nvmrc
> Do not specify the node version in .travis.yml

- app.coffee
Increased to match the higher limit in web, for when the 16kb limit is not enough if the doc has too many escape characters.
> increase body parser limit to 64kb

- app/coffee/HealthChecker.coffee
Once this is live the data will be stable, I will run a big mongo export query on the CI data set next week to find all the health check docs:
`db.docs.find( { $and: [ {lines: { $size: 2}}, {lines: "smoke test - delete me" }] } )`
I can then use these doc ids todo a delete in the doc ops collection and the docs collection rather than expensive query on the primary.
> also delete doc ops

- app.coffee
- app/coffee/DocArchiveManager.coffee
- app/coffee/HttpController.coffee
- app/coffee/MongoManager.coffee
- test/acceptance/coffee/DeletingDocsTests.coffee
- test/acceptance/coffee/helpers/DocstoreClient.coffee
- test/unit/coffee/DocArchiveManagerTests.coffee
- test/unit/coffee/HttpControllerTests.coffee
- test/unit/coffee/MongoManagerTests.coffee
As part of the soft-deletion work, we need a way to hard-delete docs. We don't want to keep stuff around in S3 and Mongo forever.
This adds a new endpoint to delete a doc, both from Mongo and S3 (if it is archived.) - We plan to call this once a project has been deleted for 90 days.
Blocks overleaf/web-internal#1867
cc @chrystalgriffiths
> Add endpoint to completely purge a project's documents

- app.coffee
When an error is caught by the default error handler, add the request URL to the log message.
This allows us to search the docstore logs for an id and see these errors, which would otherwise not be shown.
Fixes overleaf/issues#2135
> Log request URL on error

- Dockerfile
- Jenkinsfile
- Makefile
- buildscript.txt
- docker-compose.ci.yml
- docker-compose.yml
Update the build scripts for https://github.com/overleaf/dev-environment/pull/294
This adds a new `base` stage for the docker image.
https://github.com/overleaf/dev-environment/pull/294
- `language=es`
The eslint rules changed in the build-scripts, which required some formatting
changes. These were automatically applied by `prettier-eslint --write`.
- `spelling`
An additional tweak was required to cleanup a pending task for the unit-tests.
- `filestore`,  `spelling` and `third-party-datastore`
See https://github.com/overleaf/dev-environment/pull/294#issuecomment-584777526
for details on the added `data-dir` parameter.
Low.
We will notice any complications in regards to starting the services in staging.
> [misc] update the build scripts to 1.3.5

- config/settings.defaults.js
Make max doc length configurable via an env variable.
* overleaf/issues#2726
* Document updates
> Make max doc length configurable via an env variable

- test/unit/js/HttpControllerTests.js
Node 12 lazy loads `process`.  The sandbox module import does not play nice with that and we have to hard code it into the globals of the require call.
Similar patch from filestore: https://github.com/overleaf/filestore/pull/101/commits/1b408cc2572555712094b0a7a4ca651d6f99810f
Low, affects unit tests only.
cc @jdleesmiller
> [misc] test/unit: fix process usage for node v12

- .eslintrc
- .prettierrc
- Dockerfile
- Makefile
- app.js
- app/js/DocArchiveManager.js
- app/js/DocManager.js
- app/js/Errors.js
- app/js/HealthChecker.js
- app/js/HttpController.js
- app/js/MongoManager.js
- app/js/RangeManager.js
- buildscript.txt
- docker-compose.ci.yml
- docker-compose.yml
- package.json
- test/acceptance/js/ArchiveDocsTests.js
- test/acceptance/js/DeletingDocsTests.js
- test/acceptance/js/GettingAllDocsTests.js
- test/acceptance/js/GettingDocsTests.js
- test/acceptance/js/UpdatingDocsTests.js
- test/acceptance/js/helpers/DocstoreApp.js
- test/acceptance/js/helpers/DocstoreClient.js
- test/unit/js/DocArchiveManagerTests.js
- test/unit/js/DocManagerTests.js
- test/unit/js/HttpControllerTests.js
- test/unit/js/MongoManagerTests.js
- test/unit/js/RangeManagerTests.js
Fix formatting by running `make format_fix`, which required and upgrade of the build scripts first to get the fix paths (`'**/*.js'` => `$PWD'/**/*.js'`).
https://github.com/overleaf/issues/issues/3090
This will conflict with https://github.com/overleaf/docstore/pull/56 (which BTW you might have forgotten about @das7pad ?) So I pushed a  new branch, `ew-jpa-fix-express-deprecations-pretty` rebased on top of this one and fixing the conflicts. I'll leave it it with you to force-push the PR branch @das7pad
> Format + Build Scripts 2.2

- app.js
- app/js/HealthChecker.js
- app/js/MongoManager.js
- app/js/RangeManager.js
- app/js/mongodb.js
- app/js/mongojs.js
- package-lock.json
- package.json
- test/acceptance/js/ArchiveDocsTests.js
- test/acceptance/js/DeletingDocsTests.js
- test/acceptance/js/GettingAllDocsTests.js
- test/acceptance/js/GettingDocsTests.js
- test/acceptance/js/UpdatingDocsTests.js
- test/unit/js/DocArchiveManagerTests.js
- test/unit/js/DocManagerTests.js
- test/unit/js/HttpControllerTests.js
- test/unit/js/MongoManagerTests.js
- test/unit/js/RangeManagerTests.js
For https://github.com/overleaf/issues/issues/2907
This PR is migrating the mongo driver from mongojs to mongodb -- the native driver.
The current revision is a bit unclean as it mixes Promises with callbacks. Refactoring all of docstore for async/await is too much work to code and review at this time.
https://github.com/overleaf/issues/issues/2907
Previous migration: https://github.com/overleaf/chat/pull/53 https://github.com/overleaf/chat/pull/54 (https://github.com/overleaf/contacts/pull/49 pending in review)
The acceptance tests are accessing the db directly. I split the PR into the app-part and acceptance tests part to ease the verification of this PR -- e.g. run acceptance tests on the app-commit then on both.
_I sneaked in a `this` context fix for an acceptance test …
> [misc] migrate to the native mongo driver

- scripts/rearchive-all-docs.js
Adds a script to migrate our docstore data from S3 to GCS. It achieves this by:
* Unarchiving the data, which removes it from S3 or GCS, depending on where it is now
* Archiving the data, which archives to GCS
Also added a validation step to look for `\r` characters and null bytes, seeing as we are processing most of the data anyway.
Runs through all project IDs in order and logs out IDs as they are handled, so we can resume from the most recent project ID if necessary.
The script logs to stdout so that it can by run via `kubectl exec` with a pipe, to save having to worry about temporary files.
cc @jdleesmiller as we've talked about this previously.
Fixes overleaf/issues#3422
Uses a simple promise worker pool that will run an async function in the background for each project ID, but pause …
> Add script to migrate data from S3

- scripts/rearchive-all-docs.js
In order to assist running scripts in parallel, this adds an 'endId' parameter so that the script can be run over a specified range of IDs.
Extends #65 
I changed `$gt` to `$gte` so as not to accidentally miss items. It's safe to run it twice.
Just the script
> Add 'endId' parameter to rearchive script

- app/js/MongoManager.js
- scripts/rearchive-all-docs.js
- test/unit/js/MongoManagerTests.js
For https://github.com/overleaf/issues/issues/2907
Chained onto https://github.com/overleaf/docstore/pull/67
The native mongo driver has removed the support for a projection as second parameter for `find`/`findOne`.
This PR contains the changes of the codemod https://github.com/overleaf/dev-environment/pull/390 for transforming mongo find projections into the find options.
https://github.com/overleaf/issues/issues/2907
https://github.com/overleaf/dev-environment/pull/390
High. Affects all find queries.
- run acceptance tests
> [misc] run the codemod for moving mongo projections into options

- app/js/mongodb.js
- config/settings.defaults.js
Sibling of https://github.com/overleaf/chat/pull/60
> This PR is bringing back a changed default from mongojs that I did not spot initially.
>
>[mongojs is changing the underlying connector to the new `unifiedTopology`.](https://github.com/mongo-js/mongojs/blob/df1fb993c379ff48537d3028f6722eaf6f5db014/lib/database.js#L13)
>
>This change has been tested in staging as part of https://github.com/overleaf/issues/issues/3489
>
>I added a config option that allows us to flip back at any time in the future in case we see issues (using `MONGO_USE_UNIFIED_TOPOLOGY=false`).
Chained onto #67 
https://github.com/overleaf/chat/pull/60
https://github.com/overleaf/issues/issues/3489
https://github.com/overleaf/issues/issues/2907
High. The service does not start without a mongo connection. We were using …
> [misc] mongodb: use the new db connector by default

- app.js
- app/js/MongoManager.js
- app/js/PersistorManager.js
- package-lock.json
- package.json
- test/unit/js/HttpControllerTests.js
- test/unit/js/MongoManagerTests.js
Part of overleaf/issues#3502
Upgrades metrics to `@overleaf/metrics` as described in that ticket
I had to stub `settings-sharelatex` as SandboxedModule was complaining about it after adding this because the `coffee-script` module has now gone.
> Upgrade metrics to @overleaf/metrics'

- app/js/DocArchiveManager.js
- package-lock.json
- package.json
`tiny-async-pool` creates spurious errors in the logs. See #72  - The bug that causes the logged errors is fixed upstream in `master`, but not released.
`p-map` looks like a good alternative that does the same thing and is lightweight.
See #72 
Source of most of the log noise in overleaf/issues#3429
Pleasingly, the unit tests pass without modification. I hadn't stubbed the `asyncPool` behaviour previously.
Affects archiving/unarchiving/deletion
> Replace tiny-async-pool with p-map

- app/js/HealthChecker.js
- app/js/MongoManager.js
- app/js/mongodb.js
- config/settings.defaults.js
- test/acceptance/js/ArchiveDocsTests.js
- test/acceptance/js/DeletingDocsTests.js
- test/acceptance/js/helpers/DocstoreApp.js
- test/unit/js/MongoManagerTests.js
For https://github.com/overleaf/issues/issues/2907
Copied from https://github.com/overleaf/chat/pull/57
> Resolve the getCollection Promises once and store the result in a shared
`db` object which can get imported by all the call-sites.
>
> The http server is starting only after a Promise of `waitForDb()`
resolves. This covers the app code and the acceptance tests.
https://github.com/overleaf/issues/issues/2907
https://github.com/overleaf/chat/pull/57
This is best reviewed locally, comparing the PR revision with master prior to the mongodb-native merge.
High. All mongo interaction changed.
- editor works for a brand new project
- compiles work
- run acceptance tests
> [misc] simplify mongodb collection access using a shared db construct

- package-lock.json
- package.json
For https://github.com/overleaf/issues/issues/3502
- renamed package from `metrics-sharelatex` to `@overleaf/metrics`
- drop support for statsd backend
- decaffeinate
- compress `/metrics` response using gzip
- bump debugging agents to latest versions
- expose prometheus interfaces for custom metrics (custom tags)
- cleanup of open sockets metrics
- fix deprecation warnings for header access
For https://github.com/overleaf/issues/issues/3502
High. Incomplete metrics collection.
- create a new project
- open a project in the editor
- make changes to a document, reload the editor to check persistence
- compile a project
- open the history tab in the editor
- all services seem to be running fine in the dev-env
- check for compression on the `/metrics` endpoint:
- `$ curl …
> [misc] bump metrics module to 3.4.1

- package-lock.json
- package.json
For https://github.com/overleaf/issues/issues/3731
Installing npm packages via git is flaky (https://github.com/overleaf/third-party-references/pull/42).
This PR is switching the installation of the @overleaf/object-persistor package to a tar-ball install.
Note: The installed version is fairly out-dated. Shall I create a ticket for upgrading it (in a follow-up PR)? @gh2k 
https://github.com/overleaf/object-persistor/compare/4ca62157a2beb747e9a56da3ce1569124b90378a..master
For https://github.com/overleaf/issues/issues/3731
Low. The tests are not working without this package being properly installed, so the chance of it breaking in prod are low.
> [misc] install @overleaf/object-persistor from tar-ball

- docker-compose.ci.yml
- docker-compose.yml
Workaround for https://github.com/overleaf/issues/issues/3890
CI is failing with the latest fake-gcs version. This PR is pinning an old version that was in use locally.
https://github.com/overleaf/issues/issues/3890
Low.
- `$ make test_acceptance` passes
> [misc] fix ci -- pin fake-gcs to a compatible version

- app.js
- app/js/DocArchiveManager.js
- app/js/HttpController.js
- test/acceptance/js/ArchiveDocsTests.js
- test/acceptance/js/helpers/DocstoreClient.js
Chained onto https://github.com/overleaf/docstore/pull/83 for a CI fix
This PR is adding a route for archiving a single doc out of mongo.
The naming in DocArchiveManager.js is a bit strange now, but I did not
want to refactor the _internal_ method `archiveDoc` which takes a mongo
document as second parameter.
There is a minor opportunity for optimizing the mongo call(s) for
archiving: we should include `{ inS3: false }` in the queries instead
of filtering locally. It's been like that for years now, so it can
stay a little longer.
Low. Added route.
- see added acceptance
> [app] add a new route for archiving a single doc

- app/js/MongoManager.js
This PR is cleaning up an unused default that may incur high bandwidth/storage costs when used without care.
Without this _loop hole_ it is much simpler to reason about potential uses for deleted docs -> https://github.com/overleaf/issues/issues/3733#issuecomment-754060726.
All call-sites provide an options object.
Low. No call-site is using it.
> [misc] MongoManager: drop unused, potentially expensive default options

- app.js
- app/js/DocManager.js
- app/js/HttpController.js
- test/acceptance/js/DeletingDocsTests.js
- test/acceptance/js/helpers/DocstoreClient.js
For https://github.com/overleaf/issues/issues/3920
`/project/:project_id/doc/:doc_id/deleted` responds with:
- 404: the doc does not exist
- 200 and body `{"deleted":true}`: doc exists and is deleted
- 200 and body `{"deleted":false}`: doc exists and is not deleted
For https://github.com/overleaf/issues/issues/3920
Low. New endpoint.
-  see added acceptance tests -- includes cross project access
> [misc] add a new endpoint for querying the deleted status of a doc

- app/js/DocManager.js
- config/settings.defaults.js
- test/acceptance/js/DeletingDocsTests.js
- test/unit/js/DocManagerTests.js
Chained onto https://github.com/overleaf/docstore/pull/84
Instead of firing an additional docstore request from the deletion process in web, we can flush docs out of mongo as part of the soft deletion process.
I put this behind a feature flag in the settings for now.
I think it is worth flushing docs out of mongo no matter how large the deletedDocs array already is -- the user will not look at the doc any time soon. In case we want to flush out of mongo for those large projects only, we could pass a query flag from the http request into the DocManager. 
Low. New logic is behind feature flag.
- added acceptance test
- added unit test
> [DocManager] optionally flush docs out of mongo when deleting them

- app/js/DocArchiveManager.js
- app/js/MongoManager.js
- config/settings.defaults.js
- test/acceptance/js/ArchiveDocsTests.js
Chained onto https://github.com/overleaf/docstore/pull/85 (otherwise conflicting)
As per https://github.com/overleaf/issues/issues/3733#issuecomment-754060726 it should be safe to restore non deleted docs only.
This PR is putting a changed mongo query behind a feature flag.
The extended test suite in the acceptance tests manipulated the doc in a before handler, in order to adjust the un-archiving with the changed feature flag this needs changing into a beforeEach handler in order to get a new doc per test case.
Low. New logic is behind a feature flag.
- added acceptance test
> [DocArchiveManager] optionally do not un-archive soft deleted docs

- app.js
- app/js/DocManager.js
- app/js/HttpController.js
- app/js/MongoManager.js
- config/settings.defaults.js
- test/acceptance/js/DeletingDocsTests.js
- test/acceptance/js/helpers/DocstoreClient.js
- test/unit/js/MongoManagerTests.js
Chained onto https://github.com/overleaf/docstore/pull/91
This PR is implementing a new endpoint for getting a projects deleted docs.
Specifically we are emitting their doc name only.
The mongo query sorts by deletion date and limit the response to 2000 items (has a config option).
The data will be queried by the frontend -> joinProject real-time -> web-api -> docstore.
The frontend uses this data for the history pane (displayed in a list for restoring in projects with old-history) and also in the file-tree (I did not investigate this usage).
Chained onto https://github.com/overleaf/docstore/pull/91
The doc meta is incomplete at this time -- not all deleted docs have their name in the …
> [misc] add a new endpoint for getting deleted docs

- app.js
- app/js/DocManager.js
- app/js/Errors.js
- app/js/HttpController.js
- app/js/MongoManager.js
- package-lock.json
- package.json
- test/acceptance/js/DeletingDocsTests.js
- test/acceptance/js/helpers/DocstoreClient.js
- test/unit/js/DocManagerTests.js
- test/unit/js/HttpControllerTests.js
- test/unit/js/MongoManagerTests.js
Super seeds https://github.com/overleaf/docstore/pull/91
Per the review feedback in https://github.com/overleaf/web-internal/pull/3652, we are changing the DELETE endpoint to a PATCH request in order to add additional meta data to the doc entry in mongo.
Request validation is done with joi. I am rejecting edits after deleting a doc.
Super seeds https://github.com/overleaf/docstore/pull/91
The added unit tests for DocstoreManager.patchDoc share a large chunk with the existing DocstoreManager.deleteDoc tests, but have been adjusted to use the chai/sinon integration: `stub.calledWith(...).should.equal(boolean)`  -> `expect(stub).to[.not].have.been.called[With(...)]`
Low. Existing endpoints …
> [misc] add a new endpoint for changing a docs meta data -- incl. deleted

- app/js/DocArchiveManager.js
- app/js/MongoManager.js
- config/settings.defaults.js
- test/unit/js/DocArchiveManagerTests.js
For https://digital-science.slack.com/archives/G6256GXGS/p1618503789429100?thread_ts=1618478997.407500&cid=G6256GXGS
We need to cleanup a very large number of docs for a project. Loading all the doc ids into memory OOM kills the pod. This PR is implementing a batched processing. 
This may help with cleaning up large projects in production too.
Bonus: All the parameter are configurable through settings now.
For https://digital-science.slack.com/archives/G6256GXGS/p1618503789429100?thread_ts=1618478997.407500&cid=G6256GXGS
Low.
- run tests
> [DocArchiveManager] destroy in small batches

- app/js/MongoManager.js
- test/unit/js/MongoManagerTests.js
Depends on https://github.com/overleaf/web-internal/pull/3907
Chained onto https://github.com/overleaf/docstore/pull/99
This PR is dropping the `name` filter on deleted docs which safe-guards against incomplete responses while the deleted docs are not yet fully back-filled. After https://github.com/overleaf/web-internal/pull/3907 they will all have a `name`.
Depends on https://github.com/overleaf/web-internal/pull/3907
Chained onto https://github.com/overleaf/docstore/pull/99
Low.
> [MongoManager] drop name filter from getProjectsDeletedDocs

- .eslintrc
- buildscript.txt
- package-lock.json
- package.json
For https://github.com/overleaf/issues/issues/3851
Uses https://github.com/overleaf/dev-environment/pull/470
> This PR is adding linting rules for flagging imports from npm that are not properly specified in the package.json. Either they are missing at all and the `node_modules/` entry is there by chance via another dependency, or they are specified in the wrong section, e.g. using a `devDependency` in `app/js/`.
For https://github.com/overleaf/issues/issues/3851
Uses https://github.com/overleaf/dev-environment/pull/470
Low.
> [misc] add linting for missing explicit dependencies and fix any errors

- app/js/DocArchiveManager.js
- config/settings.defaults.js
- test/unit/js/DocArchiveManagerTests.js
For https://github.com/overleaf/issues/issues/4252
For https://digital-science.slack.com/archives/G6256GXGS/p1620206798002500?thread_ts=1619600805.001300&cid=G6256GXGS
This PR is adding retries to the deletion of archives in GCS/S3/... There is config options for the retry count which defaults to 3, so one failure plus 3 more tries. Eventually it will throw the last error.
For https://github.com/overleaf/issues/issues/4252
For https://digital-science.slack.com/archives/G6256GXGS/p1620206798002500?thread_ts=1619600805.001300&cid=G6256GXGS
Low.
- see added unit tests
> [DocArchiveManager] retry the deletion of doc archives three times

- app/js/DocArchiveManager.js
- app/js/MongoManager.js
- config/settings.defaults.js
- test/unit/js/DocArchiveManagerTests.js
For https://github.com/overleaf/issues/issues/4424
Similar to https://github.com/overleaf/docstore/pull/101
This PR is changing the (un-)archiving process to batched processing to allow BIG projects to go through.
For https://github.com/overleaf/issues/issues/4424
Similar to https://github.com/overleaf/docstore/pull/101
Similar to https://github.com/overleaf/docstore/pull/101
I am also removing the already partly broken 404 logic in case no archived/unarchived docs were found. This is not correct anymore after moving to db-side filtering of docs. 
The default batch size is 50, which translated into a worst case memory usage of about `50 * (7MB ranges + 2MB lines) = 450MB`.
High. DB might fill up.
- see adjusted unit tests
- acceptance tests cover this logic
> [DocArchiveManager] (un-)archive docs in batches and let db filter docs

- app.js
- app/js/DocArchiveManager.js
- app/js/DocManager.js
- app/js/Errors.js
- app/js/HttpController.js
- app/js/MongoManager.js
- test/acceptance/js/ArchiveDocsTests.js
- test/acceptance/js/GettingDocsFromArchiveTest.js
- test/acceptance/js/helpers/DocstoreClient.js
- test/setup.js
- test/unit/js/MongoManagerTests.js
This PR adds a `peek` method to retrieve a doc from mongo or persistent storage without unarchiving it.
N/A
https://github.com/overleaf/issues/issues/4539
Used by https://github.com/overleaf/track-changes/pull/117
I've tried to minimise changes to the existing code paths.
The one change I did make was to refactor `DocArchiveManager` to split the `unarchiveDoc` method into `getDoc` and `unarchiveDoc` methods, so that we can use the same code to fetch the doc without unarchiving it.
The changes for that are in the first commit "refactor unarchiveDoc to use a separate getDoc helper".
The second commit adds the `peek` methods.
I've also added a `withRevCheck` method to allow for optimistic locking.  Currently we don't have reliable locking in docstore when projects move between mongo and …
> retrieve doc without unarchiving
